"""
Layer 1 — Cross-Sectional Ranker.

The single most important upgrade vs. upstream Azalyst. Replaces per-asset z-score
filtering (`Z_THRESHOLD=1.8` in price_scanner.py) with universe-wide ranking on
risk-adjusted return, residualized against benchmark.

Output is the leaderboard the user reads manually, generated by code.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd
import yfinance as yf

from . import ETF_UNIVERSE


@dataclass(frozen=True)
class RankRow:
    ticker: str
    rank_5d: int
    rank_20d: int
    rank_60d: int
    composite_rank: int
    risk_adj_5d: float
    risk_adj_20d: float
    excess_5d: float          # vs. SPY
    excess_20d: float
    rank_stability: int       # consecutive days in top decile
    score: float              # 0-25 contribution to scorer_v2


def _download(tickers: list[str], period: str = "120d") -> pd.DataFrame:
    raw = yf.download(
        tickers, period=period, interval="1d",
        auto_adjust=True, progress=False, threads=True,
    )
    if isinstance(raw.columns, pd.MultiIndex):
        return raw["Close"].dropna(how="all", axis=1)
    return raw[["Close"]].rename(columns={"Close": tickers[0]})


def _risk_adjusted_return(close: pd.DataFrame, lookback: int) -> pd.Series:
    """Lookback return divided by realized vol over same window."""
    rets = close.pct_change()
    cum = (1 + rets).rolling(lookback).apply(np.prod, raw=True) - 1
    vol = rets.rolling(lookback).std() * np.sqrt(252)
    latest_cum = cum.iloc[-1]
    latest_vol = vol.iloc[-1].replace(0, np.nan)
    return latest_cum / latest_vol


def _excess_vs_benchmark(close: pd.DataFrame, lookback: int, benchmark: str = "SPY") -> pd.Series:
    rets = close.pct_change()
    cum = (1 + rets).rolling(lookback).apply(np.prod, raw=True) - 1
    bench = cum[benchmark] if benchmark in cum.columns else 0.0
    return (cum.iloc[-1] - (bench.iloc[-1] if hasattr(bench, "iloc") else bench))


def _rank_stability(close: pd.DataFrame, lookback: int = 5, top_decile_cutoff: float = 0.10) -> pd.Series:
    """Number of consecutive recent days each ticker has been in the top decile by 5D risk-adj return."""
    rets = close.pct_change()
    rolling_5d = (1 + rets).rolling(5).apply(np.prod, raw=True) - 1
    rolling_vol = rets.rolling(5).std() * np.sqrt(252)
    risk_adj = (rolling_5d / rolling_vol.replace(0, np.nan)).iloc[-lookback:]
    n = len(risk_adj.columns)
    cutoff_rank = int(n * top_decile_cutoff)
    daily_top_decile = risk_adj.rank(axis=1, ascending=False) <= cutoff_rank
    streak = pd.Series(0, index=close.columns)
    for ticker in close.columns:
        s = 0
        for v in daily_top_decile[ticker].iloc[::-1]:
            if v:
                s += 1
            else:
                break
        streak[ticker] = s
    return streak


def rank_universe(
    tickers: list[str] | None = None,
    benchmark: str = "SPY",
) -> list[RankRow]:
    universe = list(dict.fromkeys((tickers or ETF_UNIVERSE) + [benchmark]))
    close = _download(universe)
    if close.empty or len(close) < 60:
        return []

    ra5 = _risk_adjusted_return(close, 5)
    ra20 = _risk_adjusted_return(close, 20)
    ra60 = _risk_adjusted_return(close, 60)
    ex5 = _excess_vs_benchmark(close, 5, benchmark)
    ex20 = _excess_vs_benchmark(close, 20, benchmark)
    stab = _rank_stability(close)

    df = pd.DataFrame({
        "ra5": ra5, "ra20": ra20, "ra60": ra60,
        "ex5": ex5, "ex20": ex20, "stab": stab,
    }).dropna()
    df = df.drop(index=benchmark, errors="ignore")

    df["rank_5d"] = df["ra5"].rank(ascending=False, method="min").astype(int)
    df["rank_20d"] = df["ra20"].rank(ascending=False, method="min").astype(int)
    df["rank_60d"] = df["ra60"].rank(ascending=False, method="min").astype(int)
    df["composite_rank"] = (
        0.5 * df["rank_5d"] + 0.3 * df["rank_20d"] + 0.2 * df["rank_60d"]
    ).rank(method="min").astype(int)

    n = len(df)
    df["score"] = (
        12 * (1 - (df["rank_5d"] - 1) / max(n - 1, 1)) +
        8 * (1 - (df["rank_20d"] - 1) / max(n - 1, 1)) +
        5 * np.minimum(df["stab"] / 3.0, 1.0)
    ).clip(0, 25)

    df = df.sort_values("composite_rank")
    return [
        RankRow(
            ticker=t,
            rank_5d=int(df.at[t, "rank_5d"]),
            rank_20d=int(df.at[t, "rank_20d"]),
            rank_60d=int(df.at[t, "rank_60d"]),
            composite_rank=int(df.at[t, "composite_rank"]),
            risk_adj_5d=float(df.at[t, "ra5"]),
            risk_adj_20d=float(df.at[t, "ra20"]),
            excess_5d=float(df.at[t, "ex5"]),
            excess_20d=float(df.at[t, "ex20"]),
            rank_stability=int(df.at[t, "stab"]),
            score=float(df.at[t, "score"]),
        )
        for t in df.index
    ]


def top_n(rows: list[RankRow], n: int = 10) -> list[RankRow]:
    return sorted(rows, key=lambda r: r.composite_rank)[:n]


def to_dataframe(rows: list[RankRow]) -> pd.DataFrame:
    return pd.DataFrame([r.__dict__ for r in rows])


if __name__ == "__main__":
    rows = rank_universe()
    print(to_dataframe(top_n(rows, 15)).to_string(index=False))
